CREATE TABLE `prefijos_telefonicos_argentina` (
  `ID` int(11) NOT NULL  auto_increment ,
  `Prefijo` int(11),
  `Localidad` varchar(255),
  PRIMARY KEY  (`ID`)
);
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (1, 2345, '25 de Mayo (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (2, 2902, '28 de Noviembre');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (3, 2317, '9 de Julio (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (4, 3469, 'Acebal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (5, 3585, 'Adelia Maria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (6, 3865, 'Aguilares');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (7, 3827, 'Aimogasta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (8, 3438, 'Alcaraz');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (9, 3465, 'Alcorta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (10, 2225, 'Alejandro Korn');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (11, 2941, 'Allen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (12, 3571, 'Almafuerte (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (13, 3547, 'Alta Gracia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (14, 3892, 'Amaicha del Valle');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (15, 11, 'Buenos Aires y Gran Buenos Aires');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (16, 2337, 'America');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (17, 3844, 'Añatuya');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (18, 3835, 'Andalgala');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (19, 3827, 'Anillaco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (20, 3758, 'Apostoles');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (21, 3543, 'Argüello');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (22, 2478, 'Arrecifes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (23, 2353, 'Arribeños');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (24, 3576, 'Arroyito (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (25, 3402, 'Arroyo Seco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (26, 3491, 'Arrufo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (27, 2353, 'Ascencion');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (28, 2296, 'Ayacucho');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (29, 2281, 'Azul');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (30, 291, 'Bahia Blanca');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (31, 2266, 'Balcarce');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (32, 353, 'Ballesteros');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (33, 3563, 'Balnearia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (34, 3857, 'Bandera');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (35, 3329, 'Baradero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (36, 3466, 'Barrancas (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (37, 2648, 'Barreal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (38, 3722, 'Barrio los Pescadores');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (39, 3534, 'Bell Ville');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (40, 2292, 'Benito Juarez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (41, 3741, 'Bernardo de Irigoyen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (42, 2925, 'Bernasconi');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (43, 2314, 'Bolivar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (44, 3387, 'Bouchard');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (45, 3438, 'Bovril');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (46, 2342, 'Bragado');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (47, 2658, 'Buena Esperanza');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (48, 3894, 'Burruyacu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (49, 3781, 'Caa Cati');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (50, 3868, 'Cafayate');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (51, 297, 'Caleta Olivia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (52, 2335, 'Caleufu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (53, 2648, 'Calingasta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (54, 3489, 'Campana');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (55, 3846, 'Campo Gallo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (56, 3471, 'Cañada de Gomez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (57, 3463, 'Canals');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (58, 3752, 'Candelaria (Prov. Misiones)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (59, 2651, 'Candelaria (Prov. San Luis)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (60, 2226, 'Cañuelas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (61, 2323, 'Capilla del Señor');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (62, 2478, 'Capitan Sarmiento');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (63, 341, 'Carcaraña');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (64, 2936, 'Carhue');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (65, 2254, 'Carilo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (66, 2395, 'Carlos Casares');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (67, 2274, 'Carlos Spegazzini');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (68, 2357, 'Carlos Tejedor');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (69, 2273, 'Carmen de Areco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (70, 2929, 'Casbas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (71, 3464, 'Casilda');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (72, 2245, 'Castelli');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (73, 3833, 'Catamarca');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (74, 264, 'Caucete');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (75, 3491, 'Ceres');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (76, 2352, 'Chacabuco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (77, 3582, 'Chajan');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (78, 3456, 'Chajari');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (79, 3826, 'Chamical');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (80, 3721, 'Charadai');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (81, 3731, 'Charata');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (82, 2241, 'Chascomus');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (83, 3821, 'Chepes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (84, 3825, 'Chilecito');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (85, 2346, 'Chivilcoy');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (86, 2946, 'Choele Choel');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (87, 2948, 'Chos Malal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (88, 299, 'Cinco Saltos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (89, 2982, 'Claromeco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (90, 3718, 'Clorinda');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (91, 2473, 'Colon (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (92, 3447, 'Colon (Prov. Entre Rios)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (93, 2333, 'Colonia Baron');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (94, 3722, 'Colonia Benitez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (95, 3716, 'Comandante Fontana');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (96, 2962, 'Comandante Luis Piedra Buena');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (97, 2291, 'Comandante N. Otamendi');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (98, 297, 'Comodoro Rivadavia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (99, 3865, 'Concepcion (Prov. Tucuman)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (100, 3442, 'Concepcion del Uruguay');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (101, 345, 'Concordia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (102, 351, 'Cordoba');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (103, 342, 'Coronda');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (104, 2223, 'Coronel Brandsen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (105, 2921, 'Coronel Dorrego');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (106, 3582, 'Coronel Moldes (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (107, 2922, 'Coronel Pringles');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (108, 2926, 'Coronel Suarez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (109, 2265, 'Coronel Vidal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (110, 3468, 'Corral de Bustos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (111, 3783, 'Corrientes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (112, 3541, 'Cosquin');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (113, 3467, 'Cruz Alta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (114, 3549, 'Cruz del Eje');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (115, 3774, 'Curuzu Cuatia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (116, 299, 'Cutral Co');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (117, 2316, 'Daireaux');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (118, 2924, 'Darregueira');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (119, 3521, 'Dean Funes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (120, 2626, 'Desaguadero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (121, 2245, 'Dolores (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (122, 2317, 'Dudignac');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (123, 2334, 'Eduardo Castex');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (124, 2902, 'El Calafate');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (125, 3783, 'El Sombrero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (126, 3401, 'El Trebol');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (127, 3751, 'Eldorado');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (128, 2335, 'Embajador Martini');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (129, 3488, 'Escobar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (130, 3496, 'Esperanza (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (131, 2945, 'Esquel');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (132, 3454, 'Federal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (133, 3465, 'Firmat');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (134, 3717, 'Formosa');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (135, 2337, 'Fortin Olavarria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (136, 3854, 'Frias');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (137, 3404, 'Galvez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (138, 3752, 'Garupa');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (139, 2952, 'General Acha');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (140, 2344, 'General Alvear (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (141, 2625, 'General Alvear (Prov. Mendoza)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (142, 2353, 'General Arenales');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (143, 2243, 'General Belgrano');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (144, 2245, 'General Conesa (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (145, 2931, 'General Conesa (Prov. Rio Negro)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (146, 358, 'General Deheza');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (147, 2268, 'General Guido');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (148, 3725, 'General Jose de San Martin');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (149, 2286, 'General Lamadrid');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (150, 2267, 'General Madariaga');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (151, 3711, 'General Mosconi');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (152, 2302, 'General Pico');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (153, 2356, 'General Pinto');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (154, 2265, 'General Piran');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (155, 2941, 'General Roca (Prov. Rio Negro)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (156, 237, 'General Rodriguez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (157, 3388, 'General Villegas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (158, 2224, 'Glew');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (159, 3498, 'Gobernador Crespo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (160, 2202, 'Gonzalez Catan');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (161, 3777, 'Goya');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (162, 3444, 'Gualeguay');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (163, 3446, 'Gualeguaychu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (164, 2929, 'Guamini');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (165, 2224, 'Guernica');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (166, 2933, 'Huanguelen Sur');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (167, 2336, 'Huinca Renanco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (168, 3887, 'Humahuaca');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (169, 3716, 'Ibarreta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (170, 3711, 'Ingeniero Guillermo N. Juarez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (171, 2940, 'Ingeniero Jacobacci');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (172, 2335, 'Ingeniero Luiggi');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (173, 3467, 'Inriville');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (174, 3786, 'Ituzaingo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (175, 2647, 'Jachal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (176, 3525, 'Jesus Maria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (177, 3877, 'Joaquin V. Gonzalez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (178, 2320, 'Jose C. Paz');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (179, 2354, 'Juan B. Alberdi');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (180, 2229, 'Juan Maria Gutierrez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (181, 2264, 'Juan N. Fernandez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (182, 2362, 'Junin (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (183, 2972, 'Junin de los Andes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (184, 3584, 'La Carlota');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (185, 2623, 'La Dormida');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (186, 2264, 'La Dulce');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (187, 3548, 'La Falda');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (188, 3437, 'La Paz (Prov. Entre Rios)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (189, 2626, 'La Paz (Prov. Mendoza)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (190, 221, 'La Plata');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (191, 3575, 'La Puerta (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (192, 3885, 'La Quiaca');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (193, 3822, 'La Rioja');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (194, 2655, 'La Toma');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (195, 3385, 'Laboulaye');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (196, 3783, 'Laguna Brava');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (197, 3891, 'Lamadrid');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (198, 2285, 'Laprida');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (199, 2268, 'Las Armas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (200, 2244, 'Las Flores (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (201, 3877, 'Las Lajitas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (202, 3715, 'Las Lomitas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (203, 3482, 'Las Toscas (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (204, 3533, 'Las Varillas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (205, 3754, 'Leandro N. Alem (Prov. Misiones)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (206, 3472, 'Leones');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (207, 2242, 'Lezama');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (208, 220, 'Libertad');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (209, 3886, 'Libertador General San Martin');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (210, 2355, 'Lincoln');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (211, 3497, 'Llambi Campbell');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (212, 2261, 'Loberia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (213, 2227, 'Lobos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (214, 2948, 'Loncopue');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (215, 3327, 'Lopez Camelo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (216, 2322, 'Los Cardales');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (217, 3547, 'Los Molinos (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (218, 2358, 'Los Toldos (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (219, 2323, 'Lujan (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (220, 261, 'Lujan de Cuyo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (221, 2953, 'Macachin');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (222, 3734, 'Machagai');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (223, 3476, 'Maciel');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (224, 2221, 'Magdalena');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (225, 2268, 'Maipu (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (226, 261, 'Maipu (Prov. Mendoza)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (227, 2627, 'Malargüe');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (228, 2257, 'Mar de Ajo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (229, 223, 'Mar del Plata');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (230, 3472, 'Marcos Juarez');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (231, 220, 'Marcos Paz');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (232, 3722, 'Margarita Belen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (233, 2927, 'Medanos (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (234, 261, 'Mendoza');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (235, 2324, 'Mercedes (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (236, 3773, 'Mercedes (Prov. Corrientes)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (237, 2657, 'Mercedes (Prov. San Luis)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (238, 220, 'Merlo (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (239, 2656, 'Merlo (Prov. San Luis)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (240, 3876, 'Metan');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (241, 2291, 'Miramar (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (242, 3409, 'Moises Ville');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (243, 3717, 'Mojon de Fierro');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (244, 2271, 'Monte');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (245, 3775, 'Monte Caseros');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (246, 2921, 'Monte Hermoso');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (247, 3841, 'Monte Quemado');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (248, 3891, 'Monteagudo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (249, 3863, 'Monteros');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (250, 237, 'Moreno');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (251, 3562, 'Morteros');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (252, 2656, 'Naschel');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (253, 2272, 'Navarro');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (254, 2262, 'Necochea');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (255, 299, 'Neuquen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (256, 3435, 'Nogoya');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (257, 3825, 'Nonogasta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (258, 2343, 'Norberto de la Riestra');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (259, 3861, 'Nueva Esperanza');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (260, 2342, 'O\' Brien');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (261, 3755, 'Obera');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (262, 3856, 'Ojo de Agua (Prov. Santiago del Estero)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (263, 2284, 'Olavarria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (264, 3532, 'Oliva');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (265, 3572, 'Oncativo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (266, 3878, 'Oran');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (267, 2982, 'Orense');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (268, 343, 'Parana');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (269, 3772, 'Paso de los Libres');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (270, 2928, 'Pedro Luro');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (271, 2396, 'Pehuajo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (272, 2477, 'Pergamino');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (273, 2963, 'Perito Moreno');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (274, 2923, 'Pigüe');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (275, 2242, 'Pila');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (276, 2322, 'Pilar (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (277, 2254, 'Pinamar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (278, 223, 'Playa Chapadmalal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (279, 3752, 'Posadas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (280, 3734, 'Presidencia de la Plaza');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (281, 3732, 'Presidencia Roque Saenz Peña');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (282, 3722, 'Puerto Bastiani');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (283, 297, 'Puerto Deseado');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (284, 3757, 'Puerto Iguazu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (285, 2965, 'Puerto Madryn');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (286, 3743, 'Puerto Rico');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (287, 2962, 'Puerto Santa Cruz');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (288, 3722, 'Puerto Tirol');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (289, 2932, 'Punta Alta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (290, 2333, 'Quemu Quemu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (291, 3843, 'Quimili');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (292, 2651, 'Quines');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (293, 2317, 'Quiroga');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (294, 2475, 'Rafael Obligado');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (295, 3492, 'Rafaela');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (296, 3407, 'Ramallo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (297, 3869, 'Ranchillos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (298, 3861, 'Rapelli');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (299, 2297, 'Rauch');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (300, 2965, 'Rawson (Prov. Chubut)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (301, 2331, 'Realico');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (302, 3482, 'Reconquista');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (303, 3832, 'Recreo (Prov. Catamarca)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (304, 3722, 'Resistencia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (305, 3783, 'Riachuelo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (306, 3543, 'Rio Ceballos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (307, 2931, 'Rio Colorado (Prov. Rio Negro)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (308, 358, 'Rio Cuarto');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (309, 2966, 'Rio Gallegos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (310, 2964, 'Rio Grande (Prov. Tierra del Fuego)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (311, 2903, 'Rio Mayo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (312, 3574, 'Rio Primero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (313, 3572, 'Rio Segundo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (314, 3571, 'Rio Tercero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (315, 2902, 'Rio Turbio');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (316, 2935, 'Rivera');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (317, 2475, 'Rojas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (318, 341, 'Rosario');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (319, 3445, 'Rosario del Tala');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (320, 3382, 'Rufino');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (321, 3782, 'Saladas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (322, 2344, 'Saladillo (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (323, 2393, 'Salazar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (324, 2394, 'Salliquelo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (325, 3542, 'Salsacate');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (326, 387, 'Salta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (327, 2474, 'Salto');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (328, 3582, 'Sampacho');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (329, 2646, 'San Agustin del Valle Fertil');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (330, 2325, 'San Andres de Giles');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (331, 2326, 'San Antonio de Areco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (332, 2934, 'San Antonio Oeste');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (333, 2257, 'San Bernardo (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (334, 3404, 'San Carlos Centro');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (335, 2944, 'San Carlos de Bariloche');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (336, 2252, 'San Clemente del Tuyu');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (337, 3408, 'San Cristobal');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (338, 3564, 'San Francisco (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (339, 3522, 'San Francisco del Chañar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (340, 3754, 'San Javier (Prov. Misiones)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (341, 3405, 'San Javier (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (342, 3406, 'San Jorge (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (343, 3458, 'San Jose de Feliciano');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (344, 264, 'San Juan');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (345, 2962, 'San Julian');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (346, 3498, 'San Justo (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (347, 3476, 'San Lorenzo (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (348, 2652, 'San Luis (Prov. San Luis)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (349, 3783, 'San Luis del Palmar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (350, 2261, 'San Manuel (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (351, 2623, 'San Martin (Prov. Mendoza)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (352, 264, 'San Martin (Prov. San Juan)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (353, 2972, 'San Martin de los Andes');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (354, 381, 'San Miguel de Tucuman');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (355, 3461, 'San Nicolas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (356, 3329, 'San Pedro (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (357, 3884, 'San Pedro (Prov. Jujuy)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (358, 2627, 'San Rafael (Prov. Mendoza)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (359, 388, 'San Salvador de Jujuy');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (360, 2225, 'San Vicente (Prov. Buenos Aires)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (361, 3783, 'Santa Ana (Prov. Corrientes)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (362, 223, 'Santa Clara del Mar');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (363, 342, 'Santa Fe');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (364, 3838, 'Santa Maria (Prov. Catamarca)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (365, 2954, 'Santa Rosa (Prov. la Pampa)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (366, 3546, 'Santa Rosa de Calamuchita');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (367, 3460, 'Santa Teresa (Prov. Santa Fe)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (368, 2246, 'Santa Teresita');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (369, 385, 'Santiago del Estero');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (370, 3756, 'Santo Tome');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (371, 2934, 'Sierra Grande');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (372, 2324, 'Suipacha');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (373, 3856, 'Sumampa');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (374, 3493, 'Sunchales');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (375, 3855, 'Suncho Corral');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (376, 3867, 'Tafi del Valle');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (377, 2293, 'Tandil');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (378, 2283, 'Tapalque');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (379, 3875, 'Tartagal (Prov. Salta)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (380, 3858, 'Termas de Rio Hondo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (381, 2656, 'Tilisarao');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (382, 3837, 'Tinogasta');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (383, 3846, 'Tintina');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (384, 3471, 'Tortugas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (385, 3862, 'Trancas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (386, 3576, 'Transito');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (387, 2965, 'Trelew');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (388, 2392, 'Trenque Lauquen');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (389, 2983, 'Tres Arroyos');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (390, 2394, 'Tres Lomas');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (391, 2622, 'Tunuyan');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (392, 3543, 'Unquillo');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (393, 2901, 'Ushuaia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (394, 2624, 'Uspallata');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (395, 2354, 'Vedia');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (396, 3462, 'Venado Tuerto');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (397, 3483, 'Vera');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (398, 2221, 'Veronica');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (399, 3436, 'Victoria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (400, 2338, 'Victorica');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (401, 3583, 'Vicuña Mackenna');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (402, 2920, 'Viedma');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (403, 3735, 'Villa Angela');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (404, 2625, 'Villa Atuel');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (405, 3541, 'Villa Carlos Paz');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (406, 3400, 'Villa Constitucion');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (407, 3522, 'Villa de Maria de Rio Seco');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (408, 3573, 'Villa del Rosario (Prov. Cordoba)');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (409, 3524, 'Villa del Totoral');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (410, 3544, 'Villa Dolores');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (411, 2255, 'Villa Gesell');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (412, 2336, 'Villa Huidobro');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (413, 2925, 'Villa Iris');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (414, 2944, 'Villa la Angostura');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (415, 353, 'Villa Maria');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (416, 2941, 'Villa Regina');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (417, 3845, 'Villa San Martin');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (418, 3455, 'Villaguay');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (419, 2928, 'Villalonga');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (420, 2265, 'Vivorata');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (421, 2333, 'Winifreda');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (422, 2942, 'Zapala');
INSERT INTO prefijos_telefonicos_argentina (ID, Prefijo, Localidad) VALUES (423, 3487, 'Zarate');
